Add : add flight app & migrate
wecode-bootcamp-korea/13-MyFakeTrip-backend pull request #1
Opened 2020-11-03 17:40 UTC by 95912gw

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- flight app 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- myrealtrip/urls.py 수정
- myrealtrip/settings.py 수정
- flight/models.py 작성 및 migrate

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-11-04 02:24 UTC, jamessoun93 requested changes

2020-11-04 02:24 UTC, jamessoun93 commented on flight/models.py
> +    logo = models.URLField()
해당필드가 url 필드면 필드명도 `logo_url` 처럼 한눈에 알기쉽게 해주시는것이 좋습니다.

2020-11-04 02:24 UTC, jamessoun93 commented on flight/models.py
> +    logo = models.URLField()
그리고 URLField 같은경우 `max_length` 를 따로 지정해주지 않으면 `default`가 `200` 으로 고정되므로 직접 넉넉하게 정해주시는게 좋을 것 같습니다.

2020-11-04 02:24 UTC, jamessoun93 commented on flight/models.py
> +    flightid       = models.CharField(max_length=45)
`flightid` 가 항공편명인가요??

2020-11-04 02:33 UTC, 95912gw commented on flight/models.py
> +    logo = models.URLField()
네 수정했습니다~

2020-11-04 02:33 UTC, 95912gw commented on flight/models.py
> +    flightid       = models.CharField(max_length=45)
네 맞습니다~

2020-11-10 08:43 UTC, soheon-lee commented on flight/views.py
> +            return JsonResponse({"message":"SUCCESS!", "start_flight": low_price }, status=200)
```python
if go:
  flight_condition = {
    'depart_date' : start_date,
    'depart' : airport_depart_name,
    'arrive' : airport_arrive_name
}
```

2020-11-10 08:43 UTC, soheon-lee commented on flight/views.py
> +            return JsonResponse({"message":"SUCCESS!", "start_flight": low_price }, status=200)
```python
if come:
  flight_condition = {
    'depart_date' : end_date,
    'depart' : airport_arrive_name,
    'arrive' : airport_depart_name
}
```

2020-11-10 08:43 UTC, soheon-lee commented on flight/views.py
> +            return JsonResponse({"message":"SUCCESS!", "start_flight": low_price }, status=200)
`"depart_date" : flight_condition['depart_date']`
`"airport_depart" : flight_condition['depart']`
`"airport_arrive": flight_condition['arrive']`

2020-11-10 11:36 UTC, 95912gw commented on flight/views.py
> +            return JsonResponse({"message":"SUCCESS!", "start_flight": low_price }, status=200)
짚어주신 부분 토대로 수정했습니다!

2020-11-10 14:07 UTC, lordmyshepherd commented
LGTM 👍

2020-11-10 14:07 UTC, merged