[ADD] 호텔 예약 api 구
wecode-bootcamp-korea/13-MyFakeTrip-backend pull request #6
Opened 2020-11-09 11:58 UTC by HwangNina

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-11-12 09:46 UTC, ulfrid commented
유닛테스트도 해주세요. 세부코드는 병민님이 한번 봐주실 겁니다.

2020-11-12 16:30 UTC, lordmyshepherd requested changes

2020-11-12 16:30 UTC, lordmyshepherd commented on hotel_booking/views.py
> +        hotel_price = [Hotel.objects.get(id = hotel).basic_price for hotel in wished_hotels]
wishist, hotel, user가 서로 관계가 없는 모델인가요?

2020-11-12 16:30 UTC, lordmyshepherd commented on hotel_booking/views.py
> +            wish_list.append(wishlist_info)
아래와 같은 방법을 고민해보세요!
```python
wish_list = WishList.objects.filter(user_id=user_id).select_related('hotel')
results = [{
               "hotel_thumbnail" : wish.hotel.thumbnail_url,
               "hotel_name" : wish.hotel.name,
               "hotel_price" : wish.hotel.basic_price,
         } for wish in wish_list ]

2020-11-13 01:58 UTC, lordmyshepherd requested changes

2020-11-13 01:58 UTC, lordmyshepherd commented on hotel_booking/views.py
> +    # @utils.signin_decorator
decorator를 주석처리하신 이유가 있을까요?

2020-11-13 02:03 UTC, HwangNina commented on hotel_booking/views.py
> +    # @utils.signin_decorator
수정했습니다8ㅅ8

2020-11-13 03:10 UTC, lordmyshepherd commented
채영님 수고 많으셨어요!

2020-11-13 03:38 UTC, lordmyshepherd commented
LGTM 👍

2020-11-13 03:38 UTC, merged