Modify : flight_checkout/view.py 수정
wecode-bootcamp-korea/13-MyFakeTrip-backend pull request #8
Opened 2020-11-12 05:39 UTC by 95912gw

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- flight_checkout app 추가
- flight_checkout/models.py 추가
- flight_checkout/views.py 추가
- flight_checkout/tests.py 추가
	
	 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

flight_checkout/views.py 추가
- 항공권 예약 구현
- 마이페이지에서 예약된 항공권을 확인 가능하도록 구현

flight_checkout/tests.py 추가
- 이상해요

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- views 로직 줄일 수 있을까요?_? 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2020-11-12 13:02 UTC, lordmyshepherd requested changes

2020-11-12 13:02 UTC, lordmyshepherd commented on flight_checkout/tests.py
> +    maxDiff = None
?

2020-11-12 13:02 UTC, lordmyshepherd commented on flight_checkout/tests.py
> +    maxDiff = None
알려주세요

2020-11-12 13:02 UTC, lordmyshepherd commented on flight_checkout/views.py
> +                    end_flight_id   = Flight.objects.get(id = data['end_flight_id']).id,
matching query가 존재하지 않을 경우 발생할 수 있는 error를 추가해주세요

2020-11-12 13:02 UTC, lordmyshepherd commented on flight_checkout/views.py
> +        booked_flight   = BookingInfo.objects.select_related("user", "start_flight", "end_flight").get(user_id = user_id)
```suggestion
        booking_info = BookingInfo.objects.select_related("user", "start_flight", "end_flight").get(user_id = user_id)
        flight    = Flight.objects.select_related("airline","airport_depart","airport_arrive").get(id = start_flight_id)
        
        start_flight_id = booking_info.start_flight_id
        end_flight_id   = booking_info.end_flight_id
        start_flight  = flight.start_flight  
        end_flight      = ...

2020-11-12 13:12 UTC, 95912gw commented on flight_checkout/tests.py
> +    maxDiff = None
^-^.....

2020-11-12 13:13 UTC, 95912gw commented on flight_checkout/views.py
> +                    end_flight_id   = Flight.objects.get(id = data['end_flight_id']).id,
추가했습니다~

2020-11-13 01:59 UTC, 95912gw commented on flight_checkout/views.py
> +        booked_flight   = BookingInfo.objects.select_related("user", "start_flight", "end_flight").get(user_id = user_id)
수정했습니다~

2020-11-13 02:03 UTC, lordmyshepherd approved these changes

2020-11-13 02:03 UTC, lordmyshepherd commented on flight_checkout/views.py
> +        except ObjectDoesNotExist:
```suggestion
        except FLight.DoesNotExist:
```

2020-11-13 02:03 UTC, lordmyshepherd commented on flight_checkout/views.py
> +            return JsonResponse({"message": "Object_DoesNotExist"}, status=400)
```suggestion
            return JsonResponse({"message": "Fligth_DoesNotExist"}, status=400)
```

2020-11-13 02:03 UTC, lordmyshepherd commented
LGTM 👍

2020-11-13 02:03 UTC, merged